### ISSUE TITLE
Wrap Ollama API endpoints

### ISSUE THREAD

**Issue by JBGruber** [JBGruber/rollama#1]
- [x] ~[Generate a completion](https://github.com/jmorganca/ollama/blob/main/docs/api.md#generate-a-completion)~ (I don't see the point since it seems to do exactly the same as chat)
- [x] [Generate a chat completion](https://github.com/jmorganca/ollama/blob/main/docs/api.md#generate-a-chat-completion)
- [x] [Create a Model](https://github.com/jmorganca/ollama/blob/main/docs/api.md#create-a-model)
- [x] [List Local Models](https://github.com/jmorganca/ollama/blob/main/docs/api.md#list-local-models)
- [x] [Show Model Information](https://github.com/jmorganca/ollama/blob/main/docs/api.md#show-model-information)
- [x] [Copy a Model](https://github.com/jmorganca/ollama/blob/main/docs/api.md#copy-a-model)
- [x] [Delete a Model](https://github.com/jmorganca/ollama/blob/main/docs/api.md#delete-a-model)
- [x] [Pull a Model](https://github.com/jmorganca/ollama/blob/main/docs/api.md#pull-a-model)
- [ ] [Push a Model](https://github.com/jmorganca/ollama/blob/main/docs/api.md#push-a-model)
- [x] [Generate Embeddings](https://github.com/jmorganca/ollama/blob/main/docs/api.md#generate-embeddings)

**Comment by JiaZhang42** [comment]
Thank you for the great package, Johannes! It works perfectly.
Before I found this package, I tried to request the Ollama API using `httr2`, but it keeps giving this error saying the response type is "application/x-ndjson", not "application/json". Would you happen to know how to deal with it? I looked into your code but didn't figure it out.

``` r
library(tidyverse)
library(httr2)
request('http://localhost:11434/api/chat') %>% 
  req_body_json(list(
    model = 'mistral', 
    messages = list(
      list(role = 'user', 
      content = 'why is the sky blue?')
    )
  )) %>% 
  req_headers("Content-Type" = "application/json",
    "Accept" = "application/json") %>%
  req_error(is_error = function(resp) FALSE) %>% 
  req_perform() %>% 
  resp_body_json()
#> Error in `resp_body_json()`:
#> ! Unexpected content type "application/x-ndjson".
#> • Expecting type "application/json" or suffix "json".
```

<sup>Created on 2024-04-27 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by JiaZhang42** [comment]
> Thank you for the great package, Johannes! It works perfectly. Before I found this package, I tried to request the Ollama API using `httr2`, but it keeps giving this error saying the response type is "application/x-ndjson", not "application/json". Would you happen to know how to deal with it? I looked into your code but didn't figure it out.
> 
> ```r
> library(tidyverse)
> library(httr2)
> request('http://localhost:11434/api/chat') %>% 
>   req_body_json(list(
>     model = 'mistral', 
>     messages = list(
>       list(role = 'user', 
>       content = 'why is the sky blue?')
>     )
>   )) %>% 
>   req_headers("Content-Type" = "application/json",
>     "Accept" = "application/json") %>%
>   req_error(is_error = function(resp) FALSE) %>% 
>   req_perform() %>% 
>   resp_body_json()
> #> Error in `resp_body_json()`:
> #> ! Unexpected content type "application/x-ndjson".
> #> • Expecting type "application/json" or suffix "json".
> ```
> 
> Created on 2024-04-27 with [reprex v2.1.0](https://reprex.tidyverse.org)

Turned out I didn't set stream = FALSE. Thanks.
