### ISSUE TITLE
installation error in R 4.1.2. Error in parse(outFile) : ... unexpected input

### ISSUE THREAD

**Issue by SoaresAlisson** [JBGruber/rollama#10]
When trying to install rollama in Pop!\_Os 22.04 LTS, R version 4.1.2., I received the message

``` 
** R
Error in parse(outFile) : 
  /tmp/RtmpzhaZeL/R.INSTALL2375765f91377/rollama/R/utils.r:131:20: unexpected input
130:   status <- strsplit(rawToChar(resp), "\n")[[1]] |>
131:     grep("}$", x = _
                        ^
ERROR: unable to collate and parse R files for package ‘rollama’
```
So, I changed `pgrs` function in `lib.R` to:

```R
  status <- strsplit(rawToChar(resp), "\n")[[1]]
  status <- grep("}$", x = status, value = TRUE) |>
    textConnection() |>
    jsonlite::stream_in(verbose = FALSE, simplifyVector = FALSE)
```

And now the installation works. I think this solution is more universal than using placeholder of native pipe.

**Comment by JBGruber** [comment]
Good point. If it's that easy to make the package backwards compatible with R 4.1, we should do it. Do you want to make a PR? Otherwise I will just copy this into the source code. If you do make a PR, please add 

```r
Depends:
    R (>= 4.1.0)
```

To the DESCRIPTION.
