### ISSUE TITLE
I can't get options(rollama_config) to work

### ISSUE THREAD

**Issue by reijmerniek** [JBGruber/rollama#13]
I can't really replicate it consistently,  but when i disect the function, most of the time the system message seems to be set to the one it shows in documentation: rollama_config = "You make answers understandable to a 5 year old"

When I run the code below I get NULL.

> library(rollama)
> options(rolllama_config="you are 10 years old")
> getOption("rollama_config", default = NULL)
NULL

**Comment by JBGruber** [comment]
> when i disect the function

I'm not sure what that means.

> `options(rolllama_config="you are 10 years old")`

You have a typo here. There should only be two l in rollama. In the line below, you spell it correctly. That is why you get NULL.
