### ISSUE TITLE
Error when pulling models from ollama

### ISSUE THREAD

**Issue by sadettindemirel** [JBGruber/rollama#14]
Hello,
First of all thank you for this great package, lately I am doing some experimentation with this package. Instead of just run pull_model(), I tried to pull llama3:instruct model but I got this error:

Error: lexical error: invalid char in json text.
          8f220ff6e389f6f8ef87a01d77c{"status":"pulling manifest"}
                     (right here) ------^

Since I am having this error, how can I pull other models such as mixtral to reproduce your text classification work [here](https://jbgruber.github.io/rollama/articles/annotation.html)

**Comment by sadettindemirel** [comment]
> Hello, First of all thank you for this great package, lately I am doing some experimentation with this package. Instead of just run pull_model(), I tried to pull llama3:instruct model but I got this error:
> 
> Error: lexical error: invalid char in json text. 8f220ff6e389f6f8ef87a01d77c{"status":"pulling manifest"} (right here) ------^
> 
> Since I am having this error, how can I pull other models such as mixtral to reproduce your text classification work [here](https://jbgruber.github.io/rollama/articles/annotation.html)

After restarting R, the error is gone, you may close the issue.

**Comment by JBGruber** [comment]
This error occurs while printing the status messages. I [fixed an issue](https://github.com/JBGruber/rollama/commit/d527fb76f4820bcad5bdc4484f48b9b4e4e92526) that looks very similar a couple of days ago. Restarting R fixes it, but you can also just install the new version or turn off the progress messages completely using `options("rollama_verbose" = FALSE)`.
