### ISSUE TITLE
Error when running the `query()` function

### ISSUE THREAD

**Issue by jobreu** [JBGruber/rollama#30]
Thanks a lot for the cool package! I tried it out but got an error when running the example from the package website `chat("why is the sky blue?")`:

```r
`Error in `map()`:
ℹ In index: 1.
Caused by error in `strsplit()`:
! nicht-character Argument
---
Backtrace:
     ▆
  1. ├─rollama::query("why is the sky blue?")
  2. │ └─purrr::walk(...)
  3. │   └─purrr::map(.x, .f, ..., .progress = .progress)
  4. │     └─purrr:::map_("list", .x, .f, ..., .progress = .progress)
  5. │       ├─purrr:::with_indexed_errors(...)
  6. │       │ └─base::withCallingHandlers(...)
  7. │       ├─purrr:::call_with_cleanup(...)
  8. │       └─rollama (local) .f(.x[[i]], ...)
  9. │         └─rollama:::screen_answer(...)
 10. │           ├─base::unlist(strsplit(x, "\n", fixed = TRUE))
 11. │           └─base::strsplit(x, "\n", fixed = TRUE)
 12. └─base::.handleSimpleError(...)
 13.   └─purrr (local) h(simpleError(msg, call))
 14.     └─cli::cli_abort(...)
 15.       └─rlang::abort(...)`
 ```
I am using R v4.4.2, rollama 0.2.0, and have the following ollama models installed: llama3.1:8b and llama3.2:latest.

**Comment by JBGruber** [comment]
I can't reproduce this. Do you maybe have a very old version of Ollama? You can check with `ping_ollama()`. I don't know why it would matter, but I also can't think of any other reason.

**Comment by jobreu** [comment]
Thx for the quick reply and looking into this! I have Ollama v0.5.1 installed.

**Comment by textspur** [comment]
I am also not able to reproduce this. Can you please share the output of  `print(sessionInfo())` after running 

`library(rollama)
ping_ollama()
chat("why is the sky blue? Answer with one sentence.")

print(sessionInfo())`

**Comment by jobreu** [comment]
I was able to fix it. I needed to specify the argument `model = "llama3.1:8b"` in the `query()` call.

**Comment by jobreu** [comment]
I was able to fix it. I needed to specify the argument `model = "llama3.1:8b"` in the `query()` call.

**Comment by JBGruber** [comment]
Thanks for reporting anyway! The error that you show is completely meaningless, which is really not great. I'm working on fixing this so people get the actuall error from Ollama and not that weird `strsplit()` issue.

**Comment by JBGruber** [comment]
Turns out, this wasn't due to one but, but *two*! #31 and #32
