### ISSUE TITLE
repeated query return differed results

### ISSUE THREAD

**Issue by whweve** [JBGruber/rollama#8]
I have repeated query openchat:latest, but return differed results.
The query even returned an answer with no, running 1s.
can you please tell me why and how i can prevent this

tribble(
  ~role,    ~content,
  "system", "Does the text discuss any specific gene with clear biological functions in the text i just input? answer yes or no"
  "user",text: Rice is sensitive to cold and can be grown only in certain climate zones. Human selection of japonica rice has extended its growth zone to regions with lower temperature, while the molecular basis of this adaptation remains unknown. Here, we identify the quantitative trait locus COLD1 that confers chilling tolerance in japonica rice. Overexpression of COLD1(jap) significantly enhances chilling tolerance, whereas rice lines with deficiency or downregulation of COLD1(jap) are sensitive to cold. COLD1 encodes a regulator of G-protein signaling that localizes on plasma membrane and endoplasmic reticulum (ER). It interacts with the G-protein α subunit to activate the Ca(2+) channel for sensing low temperature and to accelerate G-protein GTPase activity. We further identify that a SNP in COLD1, SNP2, originated from Chinese Oryza rufipogon, is responsible for the ability of COLD(jap/ind) to confer chilling tolerance, supporting the importance of COLD1 in plant adaptation."
)

> query(q,model="openchat:latest", screen = TRUE)
✔ openchat:latest is thinking ⠏ [13.6s]

── Answer from openchat:latest ───────────────────────────────────────────────────────────────────────────────────────────────────────────
Yes, the text presents an example of genetic variation in the form of a SNP (single nucleotide polymorphism) in COLD1, which is
responsible for the ability of COLD(jap/ind) to confer chilling tolerance.
> query(q,model="openchat:latest", screen = TRUE)
✔ openchat:latest is thinking ⠧ [15.6s]

── Answer from openchat:latest ───────────────────────────────────────────────────────────────────────────────────────────────────────────
Yes, the text mentions a single nucleotide polymorphism (SNP) in COLD1, SNP2, which is responsible for the ability of COLD(jap/ind) to
confer chilling tolerance. This indicates that there are genetic variations present in the text.
> query(q,model="openchat:latest", screen = TRUE)
✔ openchat:latest is thinking ⠧ [1.3s]

── Answer from openchat:latest ───────────────────────────────────────────────────────────────────────────────────────────────────────────
Yes
> query(q,model="openchat:latest", screen = TRUE)
✔ openchat:latest is thinking ⠦ [1.2s]

── Answer from openchat:latest ───────────────────────────────────────────────────────────────────────────────────────────────────────────
Yes
> query(q,model="openchat:latest", screen = TRUE)
✔ openchat:latest is thinking ⠧ [11.6s]

── Answer from openchat:latest ───────────────────────────────────────────────────────────────────────────────────────────────────────────
Yes, the text presents a specific allele variation, which is SNP2 in COLD1. This variation originated from Chinese Oryza rufipogon and is
responsible for conferring chilling tolerance.
> query(q,model="openchat:latest", screen = TRUE)
✔ openchat:latest is thinking ⠦ [1.1s]

── Answer from openchat:latest ───────────────────────────────────────────────────────────────────────────────────────────────────────────
Yes
> query(q,model="openchat:latest", screen = TRUE)
✔ openchat:latest is thinking ⠴ [1s]

── Answer from openchat:latest ───────────────────────────────────────────────────────────────────────────────────────────────────────────
No
> query(q,model="openchat:latest", screen = TRUE)
✔ openchat:latest is thinking ⠙ [16.5s]

── Answer from openchat:latest ───────────────────────────────────────────────────────────────────────────────────────────────────────────
Yes, the text presents a specific genetic variation, a SNP (single nucleotide polymorphism) in COLD1, referred to as SNP2. This genetic
variation is responsible for the ability of COLD(jap/ind) to confer chilling tolerance, highlighting its importance in plant adaptation.

The session of my R enviroment

R version 4.3.2 (2023-10-31)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 22.04.3 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.10.0 
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.10.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8      
 [8] LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

time zone: Asia/Shanghai
tzcode source: system (glibc)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ollama_0.0.0.9000  stringr_1.5.0      rollama_0.0.3.9000 tibble_3.2.1       purrr_1.0.2       

loaded via a namespace (and not attached):
 [1] crayon_1.5.2      vctrs_0.6.4       cli_3.6.1         rlang_1.1.1       stringi_1.7.12    processx_3.8.2    jsonlite_1.8.7    glue_1.6.2        prettyunits_1.2.0 rprojroot_2.0.4   pkgbuild_1.4.2   
[12] ps_1.7.5          fansi_1.0.5       rappdirs_0.3.3    lifecycle_1.0.3   httr2_1.0.0       compiler_4.3.2    pkgconfig_2.0.3   rstudioapi_0.15.0 R6_2.5.1          utf8_1.2.4        pillar_1.9.0     
[23] curl_5.1.0        callr_3.7.3       magrittr_2.0.3    tools_4.3.2       desc_1.4.2        remotes_2.5.0

**Comment by textspur** [comment]
Thank you for reaching out. We will include an example for achieving consistent results in our documentation. This can be achieved through setting specific model parameters such as seed and temperature.

Could you please try running the following code to see if it gives consistent results?

`query(q,model="openchat:latest", screen = TRUE, model_params = list(
  seed = 42,
  temperature = 0
))`


Additionally, I've added a comma and removed "text" from your tibble:

```
library(rollama)
library(tibble)
pull_model("openchat:latest")

q <- tribble(
  ~role, ~content,
  "system", "Does the text discuss any specific gene with clear biological functions in the text i just input? Answer only with yes or no.",
  "user", "Rice is sensitive to cold and can be grown only in certain climate zones. Human selection of japonica rice has extended its growth zone to regions with lower temperature, while the molecular basis of this adaptation remains unknown. Here, we identify the quantitative trait locus COLD1 that confers chilling tolerance in japonica rice. Overexpression of COLD1(jap) significantly enhances chilling tolerance, whereas rice lines with deficiency or downregulation of COLD1(jap) are sensitive to cold. COLD1 encodes a regulator of G-protein signaling that localizes on plasma membrane and endoplasmic reticulum (ER). It interacts with the G-protein α subunit to activate the Ca(2+) channel for sensing low temperature and to accelerate G-protein GTPase activity. We further identify that a SNP in COLD1, SNP2, originated from Chinese Oryza rufipogon, is responsible for the ability of COLD(jap/ind) to confer chilling tolerance, supporting the importance of COLD1 in plant adaptation."
)

query(q,model="openchat:latest", screen = TRUE, model_params = list(
  seed = 42,
  temperature = 0
))
```

**Comment by JBGruber** [comment]
I added a note and example to the documentation. I thought I already did, so thanks for letting us know!

**Comment by JBGruber** [comment]
Would it maybe make sense to have a specific option for this? We already expose a couple of configs through options: https://jbgruber.github.io/rollama/reference/rollama-options.html

So maybe it would make sense if users could set `options(rollama_seed = 42)` and then the seed is set for the rest of the session.

Additionally, should the temperature be set to 0 whenever a seed is supplied? Everyone so far was really confused that you need to set both.

**Comment by whweve** [comment]
Thanks  a lot for your warm help, it worked.
